### ISSUE TITLE
Create routes importation by Flex

### ISSUE THREAD

**Issue by cyberomulus** [cyberomulus/SiteMapGeneratorBundle#13]
Flex with auto-generated recipe don't import route.

This file should be created automatically:
```yaml
# config/routes/cyberomulus_site_map_generator.yaml

cyberomulus_sitemapgenerator:
    resource: '@CyberomulusSiteMapGeneratorBundle/Resources/config/routes.xml'
```
